### ISSUE TITLE
Unserialized nodes dont have the query function.

### ISSUE THREAD

**Issue by ricardoferreirasilva** [rse/asty-astq#1]
Greetings,

I have noticed that if we serialize a node to JSON and then deserialize it the resuling ASTY node will no longer have the query, execute , etc functions.

To reproduce:

 - Create a ASTY tree.
 - Serialize it.
 - Deserialize it.
 - Query functions no longer work

Can anyone look into this?

Thanks

**Comment by rse** [comment]
Have you really used the latest versions? I ask, because I recently tried to fix exactly this issue and for my cases it worked just fine. What version of asty-astq are you using?

**Comment by ricardoferreirasilva** [comment]
@rse I am using the lastest 1.8.8 version.

**Comment by ricardoferreirasilva** [comment]
@rse You are right, this is working with the latest version. It appears my problem was that the node resulting from the parser has the {ast , errors } objects so for that case I was running node.ast.query(...). The node resulting from a deserialization has of course no errors but I was still running node.ast.query(...). Since there was no ast property in this case I was not being able to call the query method.

You can close the issue and thanks for the fast response.!
